<div>My normal div</div>

<div class="custom-div">My custom div</div>

<style>
	.custom-div {
		@apply text-center my-0 font-medium;
	}
</style>

<a class="text-blue-600 underline" target="_blank" href="https://unocss.dev/play/?version=0.62.3&html=DwEwlgbgfAsgngAgHYHsBOBbAhgGweCYAegKgCgzRIEBjHLAZwYF4AiGgVwYBcUMBaAq1iJOPPvkjFSFIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUACLBaE3gDd6SAL5wsUCCDgByLiol06TpEgwAPSLDo2OpcADbwmDj4RCTApAAUyKhQYfQAXHAA2lSomU4SXHQwDgC0KaEYTuSIcFKh0BlOtGhOcFbVCHCh6vz6GQBEMPQw-VYAurITVBpaOlB6UHQZmTPauvpGJub08QCUU6h0ABbQMAUwS4g5zgVFpcen506NQ74wJaGkcK-v0JqkGDgJwsUDSPxKQ3UoSqVHaVBECku2VQwnkjGUED2slRomYrHY3F4Aix1wR4ikWkS10OEihGAyAEYAHQAJmxKIkaFwjSOrDASwA9AL6CAmccBTCUW1dpNKFZdkggA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjraBhjYODaMMABupv5BIeGIcrbICNZ8OKE2npZY1ja8U6g4fv3aQA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA">Link to working example</a>
